# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sekka}
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kiyoka Nishiyama"]
  s.date = %q{2010-11-29}
  s.description = %q{Sekka is a SKK like input method. Sekka server provides REST Based API. If you are SKK user, let's try it.}
  s.email = %q{kiyoka@sumibi.org}
  s.executables = ["sekka-jisyo", "sekka-server"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "COPYING",
    "README",
    "bin/sekka-jisyo",
    "bin/sekka-server",
    "emacs/http-cookies.el",
    "emacs/http-get.el",
    "emacs/sekka.el",
    "lib/sekka.ru",
    "lib/sekka/alphabet-lib.nnd",
    "lib/sekka/approximatesearch.rb",
    "lib/sekka/convert-jisyo.nnd",
    "lib/sekka/henkan.nnd",
    "lib/sekka/jisyo-db.nnd",
    "lib/sekka/kvs.rb",
    "lib/sekka/roman-lib.nnd",
    "lib/sekka/sekkaversion.rb",
    "lib/sekka/util.nnd",
    "lib/sekkaconfig.rb",
    "lib/sekkaserver.rb",
    "test/alphabet-lib.nnd",
    "test/approximate-bench.nnd",
    "test/azik-verification.nnd",
    "test/common.nnd",
    "test/henkan-main.nnd",
    "test/jisyo.nnd",
    "test/roman-lib.nnd",
    "test/skk-azik-table.nnd",
    "test/util.nnd"
  ]
  s.homepage = %q{http://github.com/kiyoka/sekka}
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.1")
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Sekka is a SKK like input method.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rubyforge>, [">= 0"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_runtime_dependency(%q<fuzzy-string-match>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<memcache-client>, [">= 0"])
      s.add_runtime_dependency(%q<nendo>, [">= 0.4.0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<tokyocabinet>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rubyforge>, [">= 0"])
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<fuzzy-string-match>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<memcache-client>, [">= 0"])
      s.add_dependency(%q<nendo>, [">= 0.4.0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<tokyocabinet>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rubyforge>, [">= 0"])
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<fuzzy-string-match>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<memcache-client>, [">= 0"])
    s.add_dependency(%q<nendo>, [">= 0.4.0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<tokyocabinet>, [">= 0"])
  end
end

