source "http://rubygems.org"
gem "jeweler2"
gem "rspec"
gem "distributed-trie"
gem "memcache-client", "     :platforms => [:mri, :rbx]
gem "jruby-memcache-client", :platforms => :jruby
gem "nendo"
gem "json"
gem "rake"
gem "ruby-progressbar"
