# frozen_string_literal: true
source "https://rubygems.org"

gem "warbler", "1.4.10"
gem "eventmachine"
gem "distributed-trie"
gem "memcachepod"
gem "nendo"
gem "json"
gem "ruby-progressbar"
gem "rack"
